// Mocks generated by Mockito 5.4.2 from annotations
// in skyscanner_api/test/src/package/skyscanner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:skyscanner_api/skyscanner_export.dart' as _i2;
import 'package:skyscanner_api/src/api/culture/model/response/currency.dart'
    as _i6;
import 'package:skyscanner_api/src/api/culture/model/response/locale.dart'
    as _i5;
import 'package:skyscanner_api/src/api/culture/model/response/nearest_culture.dart'
    as _i7;
import 'package:skyscanner_api/src/api/flight/live/model/flight_live_prices_create_response/flight_live_prices_create_response.dart'
    as _i4;
import 'package:skyscanner_api/src/api/geo/model/geo_flight_response.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SkyScannerApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkyScannerApi extends _i1.Mock implements _i2.SkyScannerApi {
  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.Future<void> initializeApiKey({required String? apiKey}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeApiKey,
          [],
          {#apiKey: apiKey},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<Map<String, dynamic>?> getCarriers() => (super.noSuchMethod(
        Invocation.method(
          #getCarriers,
          [],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
  @override
  _i3.Future<Map<String, dynamic>?> getCarsDayView(
          {_i2.ReferralEntity? entity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCarsDayView,
          [],
          {#entity: entity},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
  @override
  _i3.Future<Map<String, dynamic>?> getFlightsDayView(
          {_i2.ReferralEntity? entity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlightsDayView,
          [],
          {#entity: entity},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
  @override
  _i3.Future<_i4.FlightLivePricesCreateResponse?> createLiveSearchPoll(
          String? sessionToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLiveSearchPoll,
          [sessionToken],
        ),
        returnValue: _i3.Future<_i4.FlightLivePricesCreateResponse?>.value(),
        returnValueForMissingStub:
            _i3.Future<_i4.FlightLivePricesCreateResponse?>.value(),
      ) as _i3.Future<_i4.FlightLivePricesCreateResponse?>);
  @override
  _i3.Future<_i4.FlightLivePricesCreateResponse?> createSearchLiveFlight(
          _i2.FlightLivePricesCreateEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSearchLiveFlight,
          [entity],
        ),
        returnValue: _i3.Future<_i4.FlightLivePricesCreateResponse?>.value(),
        returnValueForMissingStub:
            _i3.Future<_i4.FlightLivePricesCreateResponse?>.value(),
      ) as _i3.Future<_i4.FlightLivePricesCreateResponse?>);
  @override
  _i3.Future<dynamic> createItineraryRefresh(
    String? sessionToken,
    Map<String, dynamic>? itineraryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createItineraryRefresh,
          [
            sessionToken,
            itineraryId,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> refreshSessionToken(String? refreshSessionToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSessionToken,
          [refreshSessionToken],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> indicativeSearch(_i2.IndicativeSearchEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #indicativeSearch,
          [entity],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<_i5.LocaleResponse?> getLocales() => (super.noSuchMethod(
        Invocation.method(
          #getLocales,
          [],
        ),
        returnValue: _i3.Future<_i5.LocaleResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.LocaleResponse?>.value(),
      ) as _i3.Future<_i5.LocaleResponse?>);
  @override
  _i3.Future<_i6.CurrencyResponse?> getCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #getCurrencies,
          [],
        ),
        returnValue: _i3.Future<_i6.CurrencyResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.CurrencyResponse?>.value(),
      ) as _i3.Future<_i6.CurrencyResponse?>);
  @override
  _i3.Future<_i2.MarketResponse?> getMarkets(String? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkets,
          [locale],
        ),
        returnValue: _i3.Future<_i2.MarketResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i2.MarketResponse?>.value(),
      ) as _i3.Future<_i2.MarketResponse?>);
  @override
  _i3.Future<_i7.NearestCulture?> getNearestCulture(String? ipAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearestCulture,
          [ipAddress],
        ),
        returnValue: _i3.Future<_i7.NearestCulture?>.value(),
        returnValueForMissingStub: _i3.Future<_i7.NearestCulture?>.value(),
      ) as _i3.Future<_i7.NearestCulture?>);
  @override
  _i3.Future<_i2.CarHireResponse?> getCarHire(
          {required _i2.CarHireEntity? carHireEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCarHire,
          [],
          {#carHireEntity: carHireEntity},
        ),
        returnValue: _i3.Future<_i2.CarHireResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i2.CarHireResponse?>.value(),
      ) as _i3.Future<_i2.CarHireResponse?>);
  @override
  _i3.Future<_i2.AutosuggestFlightResponse?> getAutosuggestFlight(
          {required _i2.AutosuggestFlightEntity? autosuggestFlightEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutosuggestFlight,
          [],
          {#autosuggestFlightEntity: autosuggestFlightEntity},
        ),
        returnValue: _i3.Future<_i2.AutosuggestFlightResponse?>.value(),
        returnValueForMissingStub:
            _i3.Future<_i2.AutosuggestFlightResponse?>.value(),
      ) as _i3.Future<_i2.AutosuggestFlightResponse?>);
  @override
  _i3.Future<_i2.HotelResponse?> getHotel(
          {required _i2.HotelEntity? hotelEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHotel,
          [],
          {#hotelEntity: hotelEntity},
        ),
        returnValue: _i3.Future<_i2.HotelResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i2.HotelResponse?>.value(),
      ) as _i3.Future<_i2.HotelResponse?>);
  @override
  _i3.Future<_i8.GeoFlightResponse?> getGeoFlights(String? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGeoFlights,
          [locale],
        ),
        returnValue: _i3.Future<_i8.GeoFlightResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i8.GeoFlightResponse?>.value(),
      ) as _i3.Future<_i8.GeoFlightResponse?>);
  @override
  _i3.Future<Map<String, dynamic>?> getGeoNearestFlights(
          {required _i2.NearestFlightEntity? nearestFlight}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGeoNearestFlights,
          [],
          {#nearestFlight: nearestFlight},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
}
